version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: naylinn123
      MYSQL_DATABASE: real_estate
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=naylinn123
      - MYSQL_DATABASE=real_estate
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql-data:
